[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 119

[tool.isort]
profile = "black"

[tool.poetry]
name = "karspexet"
version = "1.0.0"
description = ""
authors = ["KÃ¥rspexet <webmaster@karspexet.se>"]

[tool.poetry.dependencies]
django = "^3.1.5"
pyqrcode = "^1.2.1"
cssmin = "^0.2.0"
dj-database-url = "^0.5.0"
django-cms = "^3.8.0"
django-filer = "^2.0.2"
django-inline-svg = "^0.1.1"
django_sendmail_backend = "^0.1.2"
djangocms-link = "^3.0.0"
djangocms-picture = "^3.0.0"
djangocms-text-ckeditor = "^4.0.0"
gunicorn = "^20.0.4"
pdfkit = "^0.6.1"
psycopg2-binary = "^2.8.6"
python = "^3.9"
python-dateutil = "^2.8.1"
raven = "^6.10.0"
sentry-sdk = "^0.19.5"
stripe = "^2.55.1"
whitenoise = "^5.2.0"
pypng = "^0.0.21"
xhtml2pdf = "^0.2.5"

[tool.poetry.dev-dependencies]
bpython = "^0.20.1"
codacy-coverage = "^1.3.11"
factory-boy = "^3.2.0"
flake8 = "^3.8.4"
isort = "^5.7.0"
jedi = "^0.18.0"
pytest = "^6.2.5"
pytest-cov = "^2.11.1"
pytest-django = "^4.1.0"
